# from a2t2 import CatsTrie
# from a2t2Final import CatsTrie
from Assignments.Assignment2.assignment2 import CatsTrie

import unittest


class GPTTests(unittest.TestCase):
    def test_definitely_random(self):
        sentences = ['according', 'to', 'all', 'known', 'laws', 'of', 'aviation', 'there', 'is', 'no', 'way', 'a',
                     'bee', 'should', 'be', 'able', 'to', 'fly', 'its', 'wings', 'are', 'too', 'small', 'to', 'get',
                     'its', 'fat', 'little', 'body', 'off', 'the', 'ground', 'the', 'bee', 'of', 'course', 'flies',
                     'anyway', 'because', 'bees', 'dont', 'care', 'what', 'humans', 'think', 'is', 'impossible',
                     'yellow', 'black', 'yellow', 'black', 'yellow', 'black', 'yellow', 'black', 'ooh', 'black', 'and',
                     'yellow', 'lets', 'shake', 'it', 'up', 'a', 'little', 'barry', 'breakfast', 'is', 'ready',
                     'coming', 'hang', 'on', 'a', 'second', 'hello', 'barry', 'adam', 'can', 'you', 'believe', 'this',
                     'is', 'happening', 'i', 'cant', 'ill', 'pick', 'you', 'up', 'looking', 'sharp', 'use', 'the',
                     'stairs', 'your', 'father', 'paid', 'good', 'money', 'for', 'those', 'sorry', 'im', 'excited',
                     'heres', 'the', 'graduate', 'were', 'very', 'proud', 'of', 'you', 'son', 'a', 'perfect', 'report',
                     'card', 'all', 'bs', 'very', 'proud', 'ma', 'i', 'got', 'a', 'thing', 'going', 'here', 'you',
                     'got', 'lint', 'on', 'your', 'fuzz', 'ow', 'thats', 'me', 'wave', 'to', 'us', 'well', 'be', 'in',
                     'row', 'bye', 'barry', 'i', 'told', 'you', 'stop', 'flying', 'in', 'the', 'house', 'hey', 'adam',
                     'hey', 'barry', 'is', 'that', 'fuzz', 'gel', 'a', 'little', 'special', 'day', 'graduation',
                     'never', 'thought', 'id', 'make', 'it', 'three', 'days', 'grade', 'school', 'three', 'days',
                     'high', 'school', 'those', 'were', 'awkward', 'three', 'days', 'college', 'im', 'glad', 'i',
                     'took', 'a', 'day', 'and', 'hitchhiked', 'around', 'the', 'hive', 'you', 'did', 'come', 'back',
                     'different', 'hi', 'barry', 'artie', 'growing', 'a', 'mustache', 'looks', 'good', 'hear', 'about',
                     'frankie', 'yeah', 'you', 'going', 'to', 'the', 'funeral', 'no', 'im', 'not', 'going', 'everybody',
                     'knows', 'sting', 'someone', 'you', 'die', 'dont', 'waste', 'it', 'on', 'a', 'squirrel', 'such',
                     'a', 'hothead', 'i', 'guess', 'he', 'could', 'have', 'just', 'gotten', 'out', 'of', 'the', 'way',
                     'i', 'love', 'this', 'incorporating', 'an', 'amusement', 'park', 'into', 'our', 'day', 'thats',
                     'why', 'we', 'dont', 'need', 'vacations', 'boy', 'quite', 'a', 'bit', 'of', 'pomp', 'under', 'the',
                     'circumstances', 'well', 'adam', 'today', 'we', 'are', 'men', 'we', 'are', 'bee', 'men', 'amen',
                     'hallelujah', 'students', 'faculty', 'distinguished', 'bees', 'please', 'welcome', 'dean',
                     'buzzwell', 'welcome', 'new', 'hive', 'city', 'graduating', 'class', 'of', 'that', 'concludes',
                     'our', 'ceremonies', 'and', 'begins', 'your', 'career', 'at', 'honex', 'industries', 'will', 'we',
                     'pick', 'our', 'job', 'today', 'i', 'heard', 'its', 'just', 'orientation', 'heads', 'up', 'here',
                     'we', 'go', 'keep', 'your', 'hands', 'and', 'antennas', 'inside', 'the', 'tram', 'at', 'all',
                     'times', 'wonder', 'what', 'itll', 'be', 'like', 'a', 'little', 'scary', 'welcome', 'to', 'honex',
                     'a', 'division', 'of', 'honesco', 'and', 'a', 'part', 'of', 'the', 'hexagon', 'group', 'this',
                     'is', 'it', 'wow', 'wow', 'we', 'know', 'that', 'you', 'as', 'a', 'bee', 'have', 'worked', 'your',
                     'whole', 'life', 'to', 'get', 'to', 'the', 'point', 'where', 'you', 'can', 'work', 'for', 'your',
                     'whole', 'life', 'honey', 'begins', 'when', 'our', 'valiant', 'pollen', 'jocks', 'bring', 'the',
                     'nectar', 'to', 'the', 'hive', 'our', 'top', 'secret', 'formula', 'is', 'automatically', 'color',
                     'corrected', 'scent', 'adjusted', 'and', 'bubble', 'contoured', 'into', 'this', 'soothing',
                     'sweet', 'syrup', 'with', 'its', 'distinctive', 'golden', 'glow', 'you', 'know', 'as', 'honey',
                     'that', 'girl', 'was', 'hot', 'shes', 'my', 'cousin', 'she', 'is', 'yes', 'were', 'all', 'cousins',
                     'right', 'youre', 'right', 'at', 'honex', 'we', 'constantly', 'strive', 'to', 'improve', 'every',
                     'aspect', 'of', 'bee', 'existence', 'these', 'bees', 'are', 'stress', 'testing', 'a', 'new',
                     'helmet', 'technology', 'what', 'do', 'you', 'think', 'he', 'makes', 'not', 'enough', 'here', 'we',
                     'have', 'our', 'latest', 'advancement', 'the', 'krelman', 'what', 'does', 'that', 'do', 'catches',
                     'that', 'little', 'strand', 'of', 'honey', 'that', 'hangs', 'after', 'you', 'pour', 'it', 'saves',
                     'us', 'millions', 'can', 'anyone', 'work', 'on', 'the', 'krelman', 'of', 'course', 'most', 'bee',
                     'jobs', 'are', 'small', 'ones', 'but', 'bees', 'know', 'that', 'every', 'small', 'job', 'if',
                     'its', 'done', 'well', 'means', 'a', 'lot', 'but', 'choose', 'carefully', 'because', 'youll',
                     'stay', 'in', 'the', 'job', 'you', 'pick', 'for', 'the', 'rest', 'of', 'your', 'life', 'the',
                     'same', 'job', 'the', 'rest', 'of', 'your', 'life', 'i', 'didnt', 'know', 'that', 'whats', 'the',
                     'difference', 'youll', 'be', 'happy', 'to', 'know', 'that', 'bees', 'as', 'a', 'species', 'havent',
                     'had', 'one', 'day', 'off', 'in', 'million', 'years', 'so', 'youll', 'just', 'work', 'us', 'to',
                     'death', 'well', 'sure', 'try', 'wow', 'that', 'blew', 'my', 'mind', 'whats', 'the', 'difference',
                     'how', 'can', 'you', 'say', 'that', 'one', 'job', 'forever', 'thats', 'an', 'insane', 'choice',
                     'to', 'have', 'to', 'make', 'im', 'relieved', 'now', 'we', 'only', 'have', 'to', 'make', 'one',
                     'decision', 'in', 'life', 'but', 'adam', 'how', 'could', 'they', 'never', 'have', 'told', 'us',
                     'that', 'why', 'would', 'you', 'question', 'anything', 'were', 'bees', 'were', 'the', 'most',
                     'perfectly', 'functioning', 'society', 'on', 'earth', 'you', 'ever', 'think', 'maybe', 'things',
                     'work', 'a', 'little', 'too', 'well', 'here', 'like', 'what', 'give', 'me', 'one', 'example', 'i',
                     'dont', 'know', 'but', 'you', 'know', 'what', 'im', 'talking', 'about', 'please', 'clear', 'the',
                     'gate', 'royal', 'nectar', 'force', 'on', 'approach', 'wait', 'a', 'second', 'check', 'it', 'out',
                     'hey', 'those', 'are', 'pollen', 'jocks', 'wow', 'ive', 'never', 'seen', 'them', 'this', 'close',
                     'they', 'know', 'what', 'its', 'like', 'outside', 'the', 'hive', 'yeah', 'but', 'some', 'dont',
                     'come', 'back', 'hey', 'jocks', 'hi', 'jocks', 'you', 'guys', 'did', 'great', 'youre', 'monsters',
                     'youre', 'sky', 'freaks', 'i', 'love', 'it', 'i', 'love', 'it', 'i', 'wonder', 'where', 'they',
                     'were', 'i', 'dont', 'know', 'their', 'days', 'not', 'planned', 'outside', 'the', 'hive', 'flying',
                     'who', 'knows', 'where', 'doing', 'who', 'knows', 'what', 'you', 'cant', 'just', 'decide', 'to',
                     'be', 'a', 'pollen', 'jock', 'you', 'have', 'to', 'be', 'bred', 'for', 'that', 'right', 'look',
                     'thats', 'more', 'pollen', 'than', 'you', 'and', 'i', 'will', 'see', 'in', 'a', 'lifetime', 'its',
                     'just', 'a', 'status', 'symbol', 'bees', 'make', 'too', 'much', 'of', 'it', 'perhaps', 'unless',
                     'youre', 'wearing', 'it', 'and', 'the', 'ladies', 'see', 'you', 'wearing', 'it', 'those', 'ladies',
                     'arent', 'they', 'our', 'cousins', 'too', 'distant', 'distant', 'look', 'at', 'these', 'two',
                     'couple', 'of', 'hive', 'harrys', 'lets', 'have', 'fun', 'with', 'them', 'it', 'must', 'be',
                     'dangerous', 'being', 'a', 'pollen', 'jock', 'yeah', 'once', 'a', 'bear', 'pinned', 'me',
                     'against', 'a', 'mushroom', 'he', 'had', 'a', 'paw', 'on', 'my', 'throat', 'and', 'with', 'the',
                     'other', 'he', 'was', 'slapping', 'me', 'oh', 'my', 'i', 'never', 'thought', 'id', 'knock', 'him',
                     'out', 'what', 'were', 'you', 'doing', 'during', 'this', 'trying', 'to', 'alert', 'the',
                     'authorities', 'i', 'can', 'autograph', 'that', 'a', 'little', 'gusty', 'out', 'there', 'today',
                     'wasnt', 'it', 'comrades', 'yeah', 'gusty', 'were', 'hitting', 'a', 'sunflower', 'patch', 'six',
                     'miles', 'from', 'here', 'tomorrow', 'six', 'miles', 'huh', 'barry', 'a', 'puddle', 'jump', 'for',
                     'us', 'but', 'maybe', 'youre', 'not', 'up', 'for', 'it', 'maybe', 'i', 'am', 'you', 'are', 'not',
                     'were', 'going', 'at', 'j', 'gate', 'what', 'do', 'you', 'think', 'buzzy', 'boy', 'are', 'you',
                     'bee', 'enough', 'i', 'might', 'be', 'it', 'all', 'depends', 'on', 'what', 'means', 'hey', 'honex',
                     'dad', 'you', 'surprised', 'me', 'you', 'decide', 'what', 'youre', 'interested', 'in', 'well',
                     'theres', 'a', 'lot', 'of', 'choices', 'but', 'you', 'only', 'get', 'one', 'do', 'you', 'ever',
                     'get', 'bored', 'doing', 'the', 'same', 'job', 'every', 'day', 'son', 'let', 'me', 'tell', 'you',
                     'about', 'stirring', 'you', 'grab', 'that', 'stick', 'and', 'you', 'just', 'move', 'it', 'around',
                     'and', 'you', 'stir', 'it', 'around', 'you', 'get', 'yourself', 'into', 'a', 'rhythm', 'its', 'a',
                     'beautiful', 'thing', 'you', 'know', 'dad', 'the', 'more', 'i', 'think', 'about', 'it', 'maybe',
                     'the', 'honey', 'field', 'just', 'isnt', 'right', 'for', 'me', 'you', 'were', 'thinking', 'of',
                     'what', 'making', 'balloon', 'animals', 'thats', 'a', 'bad', 'job', 'for', 'a', 'guy', 'with', 'a',
                     'stinger', 'janet', 'your', 'sons', 'not', 'sure', 'he', 'wants', 'to', 'go', 'into', 'honey',
                     'barry', 'you', 'are', 'so', 'funny', 'sometimes', 'im', 'not', 'trying', 'to', 'be', 'funny',
                     'youre', 'not', 'funny', 'youre', 'going', 'into', 'honey', 'our', 'son', 'the', 'stirrer',
                     'youre', 'gonna', 'be', 'a', 'stirrer', 'no', 'ones', 'listening', 'to', 'me', 'wait', 'till',
                     'you', 'see', 'the', 'sticks', 'i', 'have', 'i', 'could', 'say', 'anything', 'right', 'now', 'im',
                     'gonna', 'get', 'an', 'ant', 'tattoo', 'lets', 'open', 'some', 'honey', 'and', 'celebrate',
                     'maybe', 'ill', 'pierce', 'my', 'thorax', 'shave', 'my', 'antennae', 'shack', 'up', 'with', 'a',
                     'grasshopper', 'get', 'a', 'gold', 'tooth', 'and', 'call', 'everybody', 'dawg', 'im', 'so',
                     'proud', 'were', 'starting', 'work', 'today', 'todays', 'the', 'day', 'come', 'on', 'all', 'the',
                     'good', 'jobs', 'will', 'be', 'gone', 'yeah', 'right', 'pollen', 'counting', 'stunt', 'bee',
                     'pouring', 'stirrer', 'front', 'desk', 'hair', 'removal', 'is', 'it', 'still', 'available', 'hang',
                     'on', 'two', 'left', 'one', 'of', 'thems', 'yours', 'congratulations', 'step', 'to', 'the', 'side',
                     'whatd', 'you', 'get', 'picking', 'crud', 'out', 'stellar', 'wow', 'couple', 'of', 'newbies',
                     'yes', 'sir', 'our', 'first', 'day', 'we', 'are', 'ready', 'make', 'your', 'choice', 'you', 'want',
                     'to', 'go', 'first', 'no', 'you', 'go', 'oh', 'my', 'whats', 'available', 'restroom', 'attendants',
                     'open', 'not', 'for', 'the', 'reason', 'you', 'think', 'any', 'chance', 'of', 'getting', 'the',
                     'krelman', 'sure', 'youre', 'on', 'im', 'sorry', 'the', 'krelman', 'just', 'closed', 'out', 'wax',
                     'monkeys', 'always', 'open', 'the', 'krelman', 'opened', 'up', 'again', 'what', 'happened', 'a',
                     'bee', 'died', 'makes', 'an', 'opening', 'see', 'hes', 'dead', 'another', 'dead', 'one', 'deady',
                     'deadified', 'two', 'more', 'dead', 'dead', 'from', 'the', 'neck', 'up', 'dead', 'from', 'the',
                     'neck', 'down', 'thats', 'life', 'oh', 'this', 'is', 'so', 'hard', 'heating', 'cooling', 'stunt',
                     'bee', 'pourer', 'stirrer', 'humming', 'inspector', 'number', 'seven', 'lint', 'coordinator',
                     'stripe', 'supervisor', 'mite', 'wrangler', 'barry', 'what', 'do', 'you', 'think', 'i', 'should',
                     'barry', 'barry', 'all', 'right', 'weve', 'got', 'the', 'sunflower', 'patch', 'in', 'quadrant',
                     'nine', 'what', 'happened', 'to', 'you', 'where', 'are', 'you', 'im', 'going', 'out', 'out', 'out',
                     'where', 'out', 'there', 'oh', 'no', 'i', 'have', 'to', 'before', 'i', 'go', 'to', 'work', 'for',
                     'the', 'rest', 'of', 'my', 'life', 'youre', 'gonna', 'die', 'youre', 'crazy', 'hello', 'another',
                     'call', 'coming', 'in', 'if', 'anyones', 'feeling', 'brave', 'theres', 'a', 'korean', 'deli', 'on',
                     'rd', 'that', 'gets', 'their', 'roses', 'today', 'hey', 'guys', 'look', 'at', 'that', 'isnt',
                     'that', 'the', 'kid', 'we', 'saw', 'yesterday', 'hold', 'it', 'son', 'flight', 'decks',
                     'restricted', 'its', 'ok', 'lou', 'were', 'gonna', 'take', 'him', 'up', 'really', 'feeling',
                     'lucky', 'are', 'you', 'sign', 'here', 'here', 'just', 'initial', 'that', 'thank', 'you', 'ok',
                     'you', 'got', 'a', 'rain', 'advisory', 'today', 'and', 'as', 'you', 'all', 'know', 'bees',
                     'cannot', 'fly', 'in', 'rain', 'so', 'be', 'careful', 'as', 'always', 'watch', 'your', 'brooms',
                     'hockey', 'sticks', 'dogs', 'birds', 'bears', 'and', 'bats', 'also', 'i', 'got', 'a', 'couple',
                     'of', 'reports', 'of', 'root', 'beer', 'being', 'poured', 'on', 'us', 'murphys', 'in', 'a', 'home',
                     'because', 'of', 'it', 'babbling', 'like', 'a', 'cicada', 'thats', 'awful', 'and', 'a', 'reminder',
                     'for', 'you', 'rookies', 'bee', 'law', 'number', 'one', 'absolutely', 'no', 'talking', 'to',
                     'humans', 'all', 'right', 'launch', 'positions', 'buzz', 'buzz', 'buzz', 'buzz', 'buzz', 'buzz',
                     'buzz', 'buzz', 'buzz', 'buzz', 'buzz', 'buzz', 'black', 'and', 'yellow', 'hello', 'you', 'ready',
                     'for', 'this', 'hot', 'shot', 'yeah', 'yeah', 'bring', 'it', 'on', 'wind', 'check', 'antennae',
                     'check', 'nectar', 'pack', 'check', 'wings', 'check', 'stinger', 'check', 'scared', 'out', 'of',
                     'my', 'shorts', 'check', 'ok', 'ladies', 'lets', 'move', 'it', 'out', 'pound', 'those', 'petunias',
                     'you', 'striped', 'stem', 'suckers', 'all', 'of', 'you', 'drain', 'those', 'flowers', 'wow', 'im',
                     'out', 'i', 'cant', 'believe', 'im', 'out', 'so', 'blue', 'i', 'feel', 'so', 'fast', 'and', 'free',
                     'box', 'kite', 'wow', 'flowers', 'this', 'is', 'blue', 'leader', 'we', 'have', 'roses', 'visual',
                     'bring', 'it', 'around', 'degrees', 'and', 'hold', 'roses', 'degrees', 'roger', 'bringing', 'it',
                     'around', 'stand', 'to', 'the', 'side', 'kid', 'its', 'got', 'a', 'bit', 'of', 'a', 'kick', 'that',
                     'is', 'one', 'nectar', 'collector', 'ever', 'see', 'pollination', 'up', 'close', 'no', 'sir', 'i',
                     'pick', 'up', 'some', 'pollen', 'here', 'sprinkle', 'it', 'over', 'here', 'maybe', 'a', 'dash',
                     'over', 'there', 'a', 'pinch', 'on', 'that', 'one', 'see', 'that', 'its', 'a', 'little', 'bit',
                     'of', 'magic', 'thats', 'amazing', 'why', 'do', 'we', 'do', 'that', 'thats', 'pollen', 'power',
                     'more', 'pollen', 'more', 'flowers', 'more', 'nectar', 'more', 'honey', 'for', 'us', 'cool', 'im',
                     'picking', 'up', 'a', 'lot', 'of', 'bright', 'yellow', 'could', 'be', 'daisies', 'dont', 'we',
                     'need', 'those', 'copy', 'that', 'visual', 'wait', 'one', 'of', 'these', 'flowers', 'seems', 'to',
                     'be', 'on', 'the', 'move', 'say', 'again', 'youre', 'reporting', 'a', 'moving', 'flower',
                     'affirmative', 'that', 'was', 'on', 'the', 'line', 'this', 'is', 'the', 'coolest', 'what', 'is',
                     'it', 'i', 'dont', 'know', 'but', 'im', 'loving', 'this', 'color', 'it', 'smells', 'good', 'not',
                     'like', 'a', 'flower', 'but', 'i', 'like', 'it', 'yeah', 'fuzzy', 'chemical', 'y', 'careful',
                     'guys', 'its', 'a', 'little', 'grabby', 'my', 'sweet', 'lord', 'of', 'bees', 'candy', 'brain',
                     'get', 'off', 'there', 'problem', 'guys', 'this', 'could', 'be', 'bad', 'affirmative', 'very',
                     'close', 'gonna', 'hurt', 'mamas', 'little', 'boy', 'you', 'are', 'way', 'out', 'of', 'position',
                     'rookie', 'coming', 'in', 'at', 'you', 'like', 'a', 'missile', 'help', 'me', 'i', 'dont', 'think',
                     'these', 'are', 'flowers', 'should', 'we', 'tell', 'him', 'i', 'think', 'he', 'knows', 'what',
                     'is', 'this', 'match', 'point', 'you', 'can', 'start', 'packing', 'up', 'honey', 'because',
                     'youre', 'about', 'to', 'eat', 'it', 'yowser', 'gross', 'theres', 'a', 'bee', 'in', 'the', 'car',
                     'do', 'something', 'im', 'driving', 'hi', 'bee', 'hes', 'back', 'here', 'hes', 'going', 'to',
                     'sting', 'me', 'nobody', 'move', 'if', 'you', 'dont', 'move', 'he', 'wont', 'sting', 'you',
                     'freeze', 'he', 'blinked', 'spray', 'him', 'granny', 'what', 'are', 'you', 'doing', 'wow', 'the',
                     'tension', 'level', 'out', 'here', 'is', 'unbelievable', 'i', 'gotta', 'get', 'home', 'cant',
                     'fly', 'in', 'rain', 'cant', 'fly', 'in', 'rain', 'cant', 'fly', 'in', 'rain', 'mayday', 'mayday',
                     'bee', 'going', 'down', 'ken', 'could', 'you', 'close', 'the', 'window', 'please', 'ken', 'could',
                     'you', 'close', 'the', 'window', 'please', 'check', 'out', 'my', 'new', 'resume', 'i', 'made',
                     'it', 'into', 'a', 'fold', 'out', 'brochure', 'you', 'see', 'folds', 'out', 'oh', 'no', 'more',
                     'humans', 'i', 'dont', 'need', 'this', 'what', 'was', 'that', 'maybe', 'this', 'time', 'this',
                     'time', 'this', 'time', 'this', 'time', 'this', 'time', 'this', 'drapes', 'that', 'is',
                     'diabolical', 'its', 'fantastic', 'its', 'got', 'all', 'my', 'special', 'skills', 'even', 'my',
                     'top', 'ten', 'favorite', 'movies', 'whats', 'number', 'one', 'star', 'wars', 'nah', 'i', 'dont',
                     'go', 'for', 'that', 'kind', 'of', 'stuff', 'no', 'wonder', 'we', 'shouldnt', 'talk', 'to', 'them',
                     'theyre', 'out', 'of', 'their', 'minds', 'when', 'i', 'leave', 'a', 'job', 'interview', 'theyre',
                     'flabbergasted', 'cant', 'believe', 'what', 'i', 'say', 'theres', 'the', 'sun', 'maybe', 'thats',
                     'a', 'way', 'out', 'i', 'dont', 'remember', 'the', 'sun', 'having', 'a', 'big', 'on', 'it', 'i',
                     'predicted', 'global', 'warming', 'i', 'could', 'feel', 'it', 'getting', 'hotter', 'at', 'first',
                     'i', 'thought', 'it', 'was', 'just', 'me', 'wait', 'stop', 'bee', 'stand', 'back', 'these', 'are',
                     'winter', 'boots', 'wait', 'dont', 'kill', 'him', 'you', 'know', 'im', 'allergic', 'to', 'them',
                     'this', 'thing', 'could', 'kill', 'me', 'why', 'does', 'his', 'life', 'have', 'less', 'value',
                     'than', 'yours', 'why', 'does', 'his', 'life', 'have', 'any', 'less', 'value', 'than', 'mine',
                     'is', 'that', 'your', 'statement', 'im', 'just', 'saying', 'all', 'life', 'has', 'value', 'you',
                     'dont', 'know', 'what', 'hes', 'capable', 'of', 'feeling', 'my', 'brochure', 'there', 'you', 'go',
                     'little', 'guy', 'im', 'not', 'scared', 'of', 'himits', 'an', 'allergic', 'thing', 'put', 'that',
                     'on', 'your', 'resume', 'brochure', 'my', 'whole', 'face', 'could', 'puff', 'up', 'make', 'it',
                     'one', 'of', 'your', 'special', 'skills', 'knocking', 'someone', 'out', 'is', 'also', 'a',
                     'special', 'skill', 'right', 'bye', 'vanessa', 'thanks', 'vanessa', 'next', 'week', 'yogurt',
                     'night', 'sure', 'ken', 'you', 'know', 'whatever', 'you', 'could', 'put', 'carob', 'chips', 'on',
                     'there', 'bye', 'supposed', 'to', 'be', 'less', 'calories', 'bye', 'i', 'gotta', 'say',
                     'something', 'she', 'saved', 'my', 'life', 'i', 'gotta', 'say', 'something', 'all', 'right',
                     'here', 'it', 'goes', 'nah', 'what', 'would', 'i', 'say', 'i', 'could', 'really', 'get', 'in',
                     'trouble', 'its', 'a', 'bee', 'law', 'youre', 'not', 'supposed', 'to', 'talk', 'to', 'a', 'human',
                     'i', 'cant', 'believe', 'im', 'doing', 'this', 'ive', 'got', 'to', 'oh', 'i', 'cant', 'do', 'it',
                     'come', 'on', 'no', 'yes', 'no', 'do', 'it', 'i', 'cant', 'how', 'should', 'i', 'start', 'it',
                     'you', 'like', 'jazz', 'no', 'thats', 'no', 'good', 'here', 'she', 'comes', 'speak', 'you', 'fool',
                     'hi', 'im', 'sorry', 'youre', 'talking', 'yes', 'i', 'know', 'youre', 'talking', 'im', 'so',
                     'sorry', 'no', 'its', 'ok', 'its', 'fine', 'i', 'know', 'im', 'dreaming', 'but', 'i', 'dont',
                     'recall', 'going', 'to', 'bed', 'well', 'im', 'sure', 'this', 'is', 'very', 'disconcerting',
                     'this', 'is', 'a', 'bit', 'of', 'a', 'surprise', 'to', 'me', 'i', 'mean', 'youre', 'a', 'bee', 'i',
                     'am', 'and', 'im', 'not', 'supposed', 'to', 'be', 'doing', 'this', 'but', 'they', 'were', 'all',
                     'trying', 'to', 'kill', 'me', 'and', 'if', 'it', 'wasnt', 'for', 'you', 'i', 'had', 'to', 'thank',
                     'you', 'its', 'just', 'how', 'i', 'was', 'raised', 'that', 'was', 'a', 'little', 'weird', 'im',
                     'talking', 'with', 'a', 'bee', 'yeah', 'im', 'talking', 'to', 'a', 'bee', 'and', 'the', 'bee',
                     'is', 'talking', 'to', 'me', 'i', 'just', 'want', 'to', 'say', 'im', 'grateful', 'ill', 'leave',
                     'now', 'wait', 'how', 'did', 'you', 'learn', 'to', 'do', 'that', 'what', 'the', 'talking', 'thing',
                     'same', 'way', 'you', 'did', 'i', 'guess', 'mama', 'dada', 'honey', 'you', 'pick', 'it', 'up',
                     'thats', 'very', 'funny', 'yeah', 'bees', 'are', 'funny', 'if', 'we', 'didnt', 'laugh', 'wed',
                     'cry', 'with', 'what', 'we', 'have', 'to', 'deal', 'with', 'anyway', 'can', 'i', 'get', 'you',
                     'something', 'like', 'what', 'i', 'dont', 'know', 'i', 'mean', 'i', 'dont', 'know', 'coffee', 'i',
                     'dont', 'want', 'to', 'put', 'you', 'out', 'its', 'no', 'trouble', 'it', 'takes', 'two', 'minutes',
                     'its', 'just', 'coffee', 'i', 'hate', 'to', 'impose', 'dont', 'be', 'ridiculous', 'actually', 'i',
                     'would', 'love', 'a', 'cup', 'hey', 'you', 'want', 'rum', 'cake', 'i', 'shouldnt', 'have', 'some',
                     'no', 'i', 'cant', 'come', 'on', 'im', 'trying', 'to', 'lose', 'a', 'couple', 'micrograms',
                     'where', 'these', 'stripes', 'dont', 'help', 'you', 'look', 'great', 'i', 'dont', 'know', 'if',
                     'you', 'know', 'anything', 'about', 'fashion', 'are', 'you', 'all', 'right', 'no', 'hes', 'making',
                     'the', 'tie', 'in', 'the', 'cab', 'as', 'theyre', 'flying', 'up', 'madison', 'he', 'finally',
                     'gets', 'there', 'he', 'runs', 'up', 'the', 'steps', 'into', 'the', 'church', 'the', 'wedding',
                     'is', 'on', 'and', 'he', 'says', 'watermelon', 'i', 'thought', 'you', 'said', 'guatemalan', 'why',
                     'would', 'i', 'marry', 'a', 'watermelon', 'is', 'that', 'a', 'bee', 'joke', 'thats', 'the', 'kind',
                     'of', 'stuff', 'we', 'do', 'yeah', 'different', 'so', 'what', 'are', 'you', 'gonna', 'do', 'barry',
                     'about', 'work', 'i', 'dont', 'know', 'i', 'want', 'to', 'do', 'my', 'part', 'for', 'the', 'hive',
                     'but', 'i', 'cant', 'do', 'it', 'the', 'way', 'they', 'want', 'i', 'know', 'how', 'you', 'feel',
                     'you', 'do', 'sure', 'my', 'parents', 'wanted', 'me', 'to', 'be', 'a', 'lawyer', 'or', 'a',
                     'doctor', 'but', 'i', 'wanted', 'to', 'be', 'a', 'florist', 'really', 'my', 'only', 'interest',
                     'is', 'flowers', 'our', 'new', 'queen', 'was', 'just', 'elected', 'with', 'that', 'same',
                     'campaign', 'slogan', 'anyway', 'if', 'you', 'look', 'theres', 'my', 'hive', 'right', 'there',
                     'see', 'it', 'youre', 'in', 'sheep', 'meadow', 'yes', 'im', 'right', 'off', 'the', 'turtle',
                     'pond', 'no', 'way', 'i', 'know', 'that', 'area', 'i', 'lost', 'a', 'toe', 'ring', 'there', 'once',
                     'why', 'do', 'girls', 'put', 'rings', 'on', 'their', 'toes', 'why', 'not', 'its', 'like',
                     'putting', 'a', 'hat', 'on', 'your', 'knee', 'maybe', 'ill', 'try', 'that', 'you', 'all', 'right',
                     'maam', 'oh', 'yeah', 'fine', 'just', 'having', 'two', 'cups', 'of', 'coffee', 'anyway', 'this',
                     'has', 'been', 'great', 'thanks', 'for', 'the', 'coffee', 'yeah', 'its', 'no', 'trouble', 'sorry',
                     'i', 'couldnt', 'finish', 'it', 'if', 'i', 'did', 'id', 'be', 'up', 'the', 'rest', 'of', 'my',
                     'life', 'are', 'you', 'can', 'i', 'take', 'a', 'piece', 'of', 'this', 'with', 'me', 'sure', 'here',
                     'have', 'a', 'crumb', 'thanks', 'yeah', 'all', 'right', 'well', 'then', 'i', 'guess', 'ill', 'see',
                     'you', 'around', 'or', 'not', 'ok', 'barry', 'and', 'thank', 'you', 'so', 'much', 'again', 'for',
                     'before', 'oh', 'that', 'that', 'was', 'nothing', 'well', 'not', 'nothing', 'but', 'anyway',
                     'this', 'cant', 'possibly', 'work', 'hes', 'all', 'set', 'to', 'go', 'we', 'may', 'as', 'well',
                     'try', 'it', 'ok', 'dave', 'pull', 'the', 'chute', 'sounds', 'amazing', 'it', 'was', 'amazing',
                     'it', 'was', 'the', 'scariest', 'happiest', 'moment', 'of', 'my', 'life', 'humans', 'i', 'cant',
                     'believe', 'you', 'were', 'with', 'humans', 'giant', 'scary', 'humans', 'what', 'were', 'they',
                     'like', 'huge', 'and', 'crazy', 'they', 'talk', 'crazy', 'they', 'eat', 'crazy', 'giant', 'things',
                     'they', 'drive', 'crazy', 'do', 'they', 'try', 'and', 'kill', 'you', 'like', 'on', 'tv', 'some',
                     'of', 'them', 'but', 'some', 'of', 'them', 'dont', 'howd', 'you', 'get', 'back', 'poodle', 'you',
                     'did', 'it', 'and', 'im', 'glad', 'you', 'saw', 'whatever', 'you', 'wanted', 'to', 'see', 'you',
                     'had', 'your', 'experience', 'now', 'you', 'can', 'pick', 'out', 'yourjob', 'and', 'be', 'normal',
                     'well', 'well', 'well', 'i', 'met', 'someone', 'you', 'did', 'was', 'she', 'bee', 'ish', 'a',
                     'wasp', 'your', 'parents', 'will', 'kill', 'you', 'no', 'no', 'no', 'not', 'a', 'wasp', 'spider',
                     'im', 'not', 'attracted', 'to', 'spiders', 'i', 'know', 'its', 'the', 'hottest', 'thing', 'with',
                     'the', 'eight', 'legs', 'and', 'all', 'i', 'cant', 'get', 'by', 'that', 'face', 'so', 'who', 'is',
                     'she', 'shes', 'human', 'no', 'no', 'thats', 'a', 'bee', 'law', 'you', 'wouldnt', 'break', 'a',
                     'bee', 'law', 'her', 'names', 'vanessa', 'oh', 'boy', 'shes', 'so', 'nice', 'and', 'shes', 'a',
                     'florist', 'oh', 'no', 'youre', 'dating', 'a', 'human', 'florist', 'were', 'not', 'dating',
                     'youre', 'flying', 'outside', 'the', 'hive', 'talking', 'to', 'humans', 'that', 'attack', 'our',
                     'homes', 'with', 'power', 'washers', 'and', 'm', 's', 'one', 'eighth', 'a', 'stick', 'of',
                     'dynamite', 'she', 'saved', 'my', 'life', 'and', 'she', 'understands', 'me', 'this', 'is', 'over',
                     'eat', 'this', 'this', 'is', 'not', 'over', 'what', 'was', 'that', 'they', 'call', 'it', 'a',
                     'crumb', 'it', 'was', 'so', 'stingin', 'stripey', 'and', 'thats', 'not', 'what', 'they', 'eat',
                     'thats', 'what', 'falls', 'off', 'what', 'they', 'eat', 'you', 'know', 'what', 'a', 'cinnabon',
                     'is', 'no', 'its', 'bread', 'and', 'cinnamon', 'and', 'frosting', 'they', 'heat', 'it', 'up',
                     'sit', 'down', 'really', 'hot', 'listen', 'to', 'me', 'we', 'are', 'not', 'them', 'were', 'us',
                     'theres', 'us', 'and', 'theres', 'them', 'yes', 'but', 'who', 'can', 'deny', 'the', 'heart',
                     'that', 'is', 'yearning', 'theres', 'no', 'yearning', 'stop', 'yearning', 'listen', 'to', 'me',
                     'you', 'have', 'got', 'to', 'start', 'thinking', 'bee', 'my', 'friend', 'thinking', 'bee',
                     'thinking', 'bee', 'thinking', 'bee', 'thinking', 'bee', 'thinking', 'bee', 'thinking', 'bee',
                     'thinking', 'bee', 'there', 'he', 'is', 'hes', 'in', 'the', 'pool', 'you', 'know', 'what', 'your',
                     'problem', 'is', 'barry', 'i', 'gotta', 'start', 'thinking', 'bee', 'how', 'much', 'longer',
                     'will', 'this', 'go', 'on', 'its', 'been', 'three', 'days', 'why', 'arent', 'you', 'working',
                     'ive', 'got', 'a', 'lot', 'of', 'big', 'life', 'decisions', 'to', 'think', 'about', 'what', 'life',
                     'you', 'have', 'no', 'life', 'you', 'have', 'no', 'job', 'youre', 'barely', 'a', 'bee', 'would',
                     'it', 'kill', 'you', 'to', 'make', 'a', 'little', 'honey', 'barry', 'come', 'out', 'your',
                     'fathers', 'talking', 'to', 'you', 'martin', 'would', 'you', 'talk', 'to', 'him', 'barry', 'im',
                     'talking', 'to', 'you', 'you', 'coming', 'got', 'everything', 'all', 'set', 'go', 'ahead', 'ill',
                     'catch', 'up', 'dont', 'be', 'too', 'long', 'watch', 'this', 'vanessa', 'were', 'still', 'here',
                     'i', 'told', 'you', 'not', 'to', 'yell', 'at', 'him', 'he', 'doesnt', 'respond', 'to', 'yelling',
                     'then', 'why', 'yell', 'at', 'me', 'because', 'you', 'dont', 'listen', 'im', 'not', 'listening',
                     'to', 'this', 'sorry', 'ive', 'gotta', 'go', 'where', 'are', 'you', 'going', 'im', 'meeting', 'a',
                     'friend', 'a', 'girl', 'is', 'this', 'why', 'you', 'cant', 'decide', 'bye', 'i', 'just', 'hope',
                     'shes', 'bee', 'ish', 'they', 'have', 'a', 'huge', 'parade', 'of', 'flowers', 'every', 'year',
                     'in', 'pasadena', 'to', 'be', 'in', 'the', 'tournament', 'of', 'roses', 'thats', 'every',
                     'florists', 'dream', 'up', 'on', 'a', 'float', 'surrounded', 'by', 'flowers', 'crowds', 'cheering',
                     'a', 'tournament', 'do', 'the', 'roses', 'compete', 'in', 'athletic', 'events', 'no', 'all',
                     'right', 'ive', 'got', 'one', 'how', 'come', 'you', 'dont', 'fly', 'everywhere', 'its',
                     'exhausting', 'why', 'dont', 'you', 'run', 'everywhere', 'its', 'faster', 'yeah', 'ok', 'i', 'see',
                     'i', 'see', 'all', 'right', 'your', 'turn', 'tivo', 'you', 'can', 'just', 'freeze', 'live', 'tv',
                     'thats', 'insane', 'you', 'dont', 'have', 'that', 'we', 'have', 'hivo', 'but', 'its', 'a',
                     'disease', 'its', 'a', 'horrible', 'horrible', 'disease', 'oh', 'my', 'dumb', 'bees']

        cattrie = CatsTrie(sentences)

        self.assertEqual(cattrie.autoComplete('c'), 'cant')
        self.assertEqual(cattrie.autoComplete('d'), 'dont')
        self.assertEqual(cattrie.autoComplete('e'), 'eat')
        self.assertEqual(cattrie.autoComplete('j'), 'just')
        self.assertEqual(cattrie.autoComplete('m'), 'my')
        self.assertEqual(cattrie.autoComplete('p'), 'pollen')
        self.assertEqual(cattrie.autoComplete('r'), 'right')
        self.assertEqual(cattrie.autoComplete('u'), 'up')
        self.assertEqual(cattrie.autoComplete('v'), 'very')
        self.assertEqual(cattrie.autoComplete('x'), None)
        self.assertEqual(cattrie.autoComplete('z'), None)

        #These Failed
        self.assertEqual(cattrie.autoComplete(''), 'you')
        self.assertEqual(cattrie.autoComplete('a'), 'a')
        self.assertEqual(cattrie.autoComplete('b'), 'bee')
        self.assertEqual(cattrie.autoComplete('f'), 'for')
        self.assertEqual(cattrie.autoComplete('g'), 'get')
        self.assertEqual(cattrie.autoComplete('h'), 'have')
        self.assertEqual(cattrie.autoComplete('i'), 'i')
        self.assertEqual(cattrie.autoComplete('k'), 'know')
        self.assertEqual(cattrie.autoComplete('l'), 'life')
        self.assertEqual(cattrie.autoComplete('o'), 'of')
        self.assertEqual(cattrie.autoComplete('q'), 'quadrant')
        self.assertEqual(cattrie.autoComplete('s'), 'so')
        self.assertEqual(cattrie.autoComplete('t'), 'the')
        self.assertEqual(cattrie.autoComplete('w'), 'what')
        self.assertEqual(cattrie.autoComplete('y'), 'you')





if __name__ == "__main__":
    unittest.main()
